name: Node Continuous Integration

on: 
  pull_request:
    branches: [main]
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: run all tests not dependent on internal server
        run: npm test -- --testPathIgnorePatterns='./tests/ServerDependentTests/*'
